import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { checkPlan, checkScope } from '../skills/websites-to-worlds/scripts/check-world.mjs';
const read = name => JSON.parse(readFileSync(new URL(`../skills/websites-to-worlds/assets/${name}.example.json`, import.meta.url)));
const plan = read('world-plan'), inventory = read('content-inventory');
assert.deepEqual(checkPlan(plan, inventory), []);
// A quiet single room needs neither connections nor a mechanism.
const study = structuredClone(plan);
study.zones = [study.zones[0]];
study.connections = [];
study.stations = [study.stations[0]];
study.beats = [study.beats[0]];
study.direction = { topology: 'One seated study', verb: 'Read', signature: 'Books beside a garden window', whyThisContent: 'A quiet setting for the author archive' };
assert.deepEqual(checkPlan(study, inventory), []);
const badAction = structuredClone(plan); delete badAction.stations[1].feedback;
assert(checkPlan(badAction, inventory).some(e => e.includes('feedback')));
const missing = structuredClone(plan); missing.stations[0].contentIds.pop();
assert(checkPlan(missing, inventory).some(e => e.includes('contact')));
const gated = structuredClone(plan); gated.stations[0].zone = 'deck'; gated.connections[0].gated = true;
assert(checkPlan(gated, inventory).some(e => e.includes('ungated')));
const isolated = structuredClone(plan); isolated.zones.push({ id: 'lost' });
assert(checkPlan(isolated, inventory).some(e => e.includes('Unreachable')));
const duplicate = structuredClone(plan); duplicate.zones.push({ id: 'deck' });
assert(checkPlan(duplicate, inventory).some(e => e.includes('duplicate')));
assert(checkPlan({ zones: [null], stations: [null], connections: [null], beats: [null] }, inventory).length);
assert(checkPlan(null, null).length);
const repo = mkdtempSync(join(tmpdir(), 'world-scope-'));
const git = (...args) => execFileSync('git', args, { cwd: repo, stdio: 'pipe' }).toString().trim();
try {
  git('init', '-q'); git('config', 'user.email', 'test@example.invalid'); git('config', 'user.name', 'Scope test');
  writeFileSync(join(repo, 'index.html'), 'original'); git('add', '.'); git('commit', '-qm', 'base');
  const base = git('rev-parse', 'HEAD');
  writeFileSync(join(repo, 'index.html'), 'unrelated redesign'); git('add', '.'); git('commit', '-qm', 'design');
  mkdirSync(join(repo, 'ship')); writeFileSync(join(repo, 'ship/main.js'), '// ship'); git('add', '.'); git('commit', '-qm', 'ship');
  assert.deepEqual(checkScope(base, ['ship'], repo).unexpected, ['index.html']);
  assert.deepEqual(checkScope(base, ['ship', 'index.html'], repo).unexpected, []);
  writeFileSync(join(repo, 'dirty.txt'), 'untracked');
  assert(checkScope(base, ['ship'], repo).unexpected.includes('dirty.txt'));
  git('add', 'dirty.txt');
  assert(checkScope(base, ['ship'], repo).unexpected.includes('dirty.txt'));
  git('mv', 'index.html', 'ship/home.html');
  assert(checkScope(base, ['ship'], repo).unexpected.includes('index.html'));
  writeFileSync(join(repo, 'ship/main.js'), '// changed locally');
  assert(checkScope('HEAD', ['index.html'], repo).unexpected.includes('ship/main.js'));
  writeFileSync(join(repo, ' leading-space.txt'), 'untracked path');
  assert(checkScope(base, ['ship'], repo).unexpected.includes(' leading-space.txt'));
  assert(checkScope(base, ['ship'], join(repo, 'ship')).unexpected.includes('dirty.txt'));
  assert.throws(() => checkScope(base, ['.'], repo));
} finally { rmSync(repo, { recursive: true, force: true }); }
console.log('Plan and whole-branch scope checks passed.');

const { smokeFailures } = await import('../skills/websites-to-worlds/scripts/probe-three-scene.mjs');
const smoke = { canvases: [{ visible: true, width: 800, height: 600 }], started: true, consoleMessages: [], networkErrors: [] };
assert.deepEqual(smokeFailures(smoke, true), []);
assert(smokeFailures({ ...smoke, canvases: [] }).length);
assert(smokeFailures({ ...smoke, started: false }, true).length);
assert(smokeFailures({ ...smoke, networkErrors: [{ status: 404 }] }).length);
assert(smokeFailures({ ...smoke, consoleMessages: [{ type: 'pageerror' }] }).length);
console.log('Smoke diagnostic checks passed (no browser launched).');
